In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
complaints = pd.read_csv("NYPD_Complaint_Data_Historic_20250530.csv")

/var/folders/0d/v5wf93vd20j3t_d7spp38m5w0000gn/T/ipykernel_16995/2951321283.py:1: DtypeWarning: Columns (0,20) have mixed types. Specify dtype option on import or set low_memory=False.
  complaints = pd.read_csv("NYPD_Complaint_Data_Historic_20250530.csv")

In [3]:
arrests = pd.read_csv("NYPD_Arrests_Data__Historic__20250530.csv")

In [4]:
complaints_sorted = complaints.sort_values(by=['CMPLNT_FR_DT','CMPLNT_FR_TM'])
complaints_sorted

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,RPT_DT,KY_CD,OFNS_DESC,PD_CD,...,SUSP_SEX,TRANSIT_DISTRICT,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
225067,47950156,01/01/1948,04:00:00,06/28/2008,02:51:00,105.0,07/02/2008,361,OFF. AGNST PUB ORD SENSBLTY &,639.0,...,(null),NaN,40.694620,-73.735327,"(40.69462, -73.735327)",PATROL BORO QUEENS SOUTH,(null),25-44,BLACK,F
6105718,226616730,01/01/1955,00:01:00,12/31/1957,00:59:00,123.0,04/07/2021,116,SEX CRIMES,177.0,...,(null),NaN,40.512038,-74.249755,"(40.5120382535219, -74.2497549524458)",PATROL BORO STATEN ISLAND,(null),65+,WHITE,F
5701972,221569468,01/01/1955,10:00:00,01/01/1967,10:00:00,62.0,12/09/2020,116,SEX CRIMES,177.0,...,M,NaN,40.602216,-74.002951,"(40.6022161657077, -74.0029507988395)",PATROL BORO BKLYN SOUTH,(null),65+,WHITE,F
6752812,249596456,01/01/1961,00:00:00,12/31/1961,23:59:00,19.0,08/15/2022,116,SEX CRIMES,177.0,...,(null),NaN,40.766996,-73.963922,"(40.7669956423899, -73.9639223035387)",PATROL BORO MAN NORTH,(null),65+,WHITE,M
6894159,252593706,01/01/1964,00:01:00,NaN,(null),42.0,10/14/2022,116,SEX CRIMES,177.0,...,M,NaN,40.822271,-73.911698,"(40.8222710411331, -73.911697780277)",PATROL BORO BRONX,(null),45-64,UNKNOWN,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2458532,92143870,NaN,23:40:00,08/14/2013,02:00:00,13.0,08/14/2013,361,OFF. AGNST PUB ORD SENSBLTY &,639.0,...,M,NaN,40.738210,-73.992011,"(40.73821, -73.992011)",PATROL BORO MAN SOUTH,(null),18-24,WHITE HISPANIC,F
8773108,47409515,NaN,23:50:00,NaN,(null),13.0,06/21/2008,344,ASSAULT 3 & RELATED OFFENSES,113.0,...,(null),NaN,40.736698,-73.983316,"(40.73669795, -73.98331594)",PATROL BORO MAN SOUTH,(null),25-44,WHITE HISPANIC,M
8071409,10987870,NaN,23:54:00,04/11/2006,00:05:00,73.0,04/11/2006,343,OTHER OFFENSES RELATED TO THEF,478.0,...,(null),NaN,40.659413,-73.913933,"(40.659413, -73.913933)",PATROL BORO BKLYN NORTH,(null),25-44,WHITE,M
2980677,139772251,NaN,23:55:00,11/21/2014,00:05:00,7.0,11/21/2014,344,ASSAULT 3 & RELATED OFFENSES,101.0,...,M,NaN,40.717864,-73.986176,"(40.717864, -73.986176)",PATROL BORO MAN SOUTH,(null),25-44,WHITE HISPANIC,M
8129642,10883958,NaN,23:55:00,NaN,(null),110.0,04/04/2006,344,ASSAULT 3 & RELATED OFFENSES,101.0,...,M,NaN,40.741451,-73.884338,"(40.741451, -73.884338)",PATROL BORO QUEENS NORTH,(null),45-64,WHITE,M

In [5]:
complaints_sorted['CMPLNT_FR_DT']=pd.to_datetime(complaints_sorted['CMPLNT_FR_DT'], errors='coerce')
complaints_sorted['CMPLNT_FR_DT'].dropna(inplace=True)

In [6]:
complaints_sorted['CMPLNT_FR_DT']

225067    1948-01-01
6105718   1955-01-01
5701972   1955-01-01
6752812   1961-01-01
6894159   1964-01-01
             ...
2458532          NaT
8773108          NaT
8071409          NaT
2980677          NaT
8129642          NaT
Name: CMPLNT_FR_DT, Length: 9491946, dtype: datetime64[ns]

In [7]:
morethandate = complaints_sorted['CMPLNT_FR_DT'] >= pd.to_datetime('2006-01-01')

In [8]:
complaints_subset = complaints_sorted[morethandate]

In [9]:

complaints_subset['LONGLAT']=complaints_subset['Longitude'].astype(str)+" "+complaints_subset['Latitude'].astype(str)
complaints_subset

/var/folders/0d/v5wf93vd20j3t_d7spp38m5w0000gn/T/ipykernel_16995/751417305.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complaints_subset['LONGLAT']=complaints_subset['Longitude'].astype(str)+" "+complaints_subset['Latitude'].astype(str)

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,RPT_DT,KY_CD,OFNS_DESC,PD_CD,...,TRANSIT_DISTRICT,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,LONGLAT
7308,45696867,2006-01-01,00:00:00,12/31/2006,23:59:00,40.0,04/14/2008,340,FRAUDS,718.0,...,NaN,40.811507,-73.922606,"(40.811507, -73.922606)",PATROL BORO BRONX,(null),25-44,BLACK,F,-73.922606 40.811507
83442,46101691,2006-01-01,00:00:00,03/01/2008,15:00:00,44.0,04/30/2008,112,THEFT-FRAUD,739.0,...,NaN,40.838528,-73.915334,"(40.838528, -73.915334)",PATROL BORO BRONX,(null),25-44,BLACK HISPANIC,F,-73.915334 40.838528
150747,52275241,2006-01-01,00:00:00,12/31/2007,00:00:00,49.0,10/16/2008,340,FRAUDS,718.0,...,NaN,40.855565,-73.865718,"(40.855565, -73.865718)",PATROL BORO BRONX,(null),25-44,UNKNOWN,M,-73.865718 40.855565
160989,38948518,2006-01-01,00:00:00,12/31/2006,00:00:00,49.0,02/05/2008,340,FRAUDS,718.0,...,NaN,40.861223,-73.860729,"(40.861223, -73.860729)",PATROL BORO BRONX,(null),25-44,WHITE HISPANIC,M,-73.860729 40.861223
169670,52517988,2006-01-01,00:00:00,12/31/2006,00:00:00,77.0,10/24/2008,116,SEX CRIMES,179.0,...,NaN,40.674496,-73.930571,"(40.6744956865259, -73.9305713255961)",PATROL BORO BKLYN NORTH,(null),<18,BLACK,F,-73.9305713255961 40.6744956865259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9375752,298704253,2024-12-31,23:25:00,12/31/2024,23:30:00,67.0,12/31/2024,118,DANGEROUS WEAPONS,792.0,...,NaN,40.657858,-73.916488,"(40.65785843797927, -73.91648767685969)",PATROL BORO BKLYN SOUTH,(null),UNKNOWN,UNKNOWN,E,-73.91648767685969 40.65785843797927
9126241,298692886,2024-12-31,23:30:00,NaN,(null),13.0,12/31/2024,107,BURGLARY,223.0,...,NaN,40.732922,-73.981277,"(40.732922, -73.981277)",PATROL BORO MAN SOUTH,(null),18-24,WHITE,F,-73.981277 40.732922
9181203,298703788,2024-12-31,23:30:00,12/31/2024,23:40:00,47.0,12/31/2024,578,HARRASSMENT 2,637.0,...,NaN,40.877125,-73.865602,"(40.877125, -73.865602)",PATROL BORO BRONX,(null),45-64,BLACK,F,-73.865602 40.877125
8996177,298704264,2024-12-31,23:37:00,12/31/2024,23:45:00,72.0,12/31/2024,106,FELONY ASSAULT,109.0,...,NaN,40.661646,-73.998435,"(40.661646, -73.998435)",PATROL BORO BKLYN SOUTH,(null),45-64,WHITE HISPANIC,F,-73.998435 40.661646
9146670,298712832,2024-12-31,23:45:00,12/31/2024,23:50:00,75.0,12/31/2024,125,OTHER STATE LAWS,847.0,...,NaN,40.656262,-73.891081,"(40.65626168022815, -73.8910808434055)",PATROL BORO BKLYN NORTH,(null),UNKNOWN,UNKNOWN,E,-73.8910808434055 40.65626168022815

In [10]:
arrests_sorted = arrests.sort_values(by=['ARREST_DATE'])
arrests_sorted

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
5985472,9929805,01/01/2006,793.0,WEAPONS POSSESSION 3,118.0,DANGEROUS WEAPONS,PL 2650204,F,B,52,0.0,25-44,M,WHITE HISPANIC,1015192.0,257668.0,40.873868,-73.888119,POINT (-73.88811877499995 40.873867549000074)
5976830,9930311,01/01/2006,750.0,RESISTING ARREST,359.0,OFFENSES AGAINST PUBLIC ADMINISTRATION,PL 2053000,M,Q,111,0.0,45-64,M,ASIAN / PACIFIC ISLANDER,1046277.0,210432.0,40.744055,-73.776156,POINT (-73.77615584299997 40.74405453100008)
5980692,9929897,01/01/2006,779.0,"PUBLIC ADMINISTRATION,UNCLASSIFIED FELONY",126.0,MISCELLANEOUS PENAL LAW,PL 215510B,F,B,40,0.0,45-64,M,BLACK,1006737.0,233009.0,40.806211,-73.918774,POINT (-73.91877372999993 40.80621138200007)
5980694,9930087,01/01/2006,567.0,"MARIJUANA, POSSESSION 4 & 5",235.0,DANGEROUS DRUGS,PL 2211001,M,M,7,0.0,25-44,M,WHITE,987478.0,201620.0,40.720085,-73.988356,POINT (-73.98835630899998 40.72008467900002)
5983584,9930095,01/01/2006,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,19,0.0,18-24,M,WHITE,996157.0,222560.0,40.777552,-73.957009,POINT (-73.95700940399996 40.77755228400008)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256186,298672654,12/31/2024,793.0,WEAPONS POSSESSION 3,118.0,DANGEROUS WEAPONS,PL 2650201,F,K,75,2.0,45-64,M,BLACK,1019192.0,183434.0,40.670101,-73.874039,POINT (-73.874039 40.670101)
255113,298699290,12/31/2024,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,Q,102,0.0,45-64,M,WHITE,1031992.0,197141.0,40.707664,-73.827801,POINT (-73.827801 40.707664)
256145,298663611,12/31/2024,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL05110E2,F,B,40,0.0,25-44,M,BLACK,1003284.0,235725.0,40.813666,-73.931238,POINT (-73.93123754706842 40.81366588249614)
12651,298690452,12/31/2024,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,B,40,0.0,25-44,M,BLACK,1009012.0,236134.0,40.814785,-73.910542,POINT (-73.910542 40.814785)
253806,298682165,12/31/2024,268.0,CRIMINAL MIS 2 & 3,121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1450502,F,Q,109,0.0,18-24,M,WHITE HISPANIC,1032084.0,216954.0,40.762045,-73.827329,POINT (-73.827329 40.762045)

In [11]:
arrests_sorted['ARREST_DATE']=pd.to_datetime(arrests_sorted['ARREST_DATE'], errors='coerce')
arrests_sorted['LONGLAT']=arrests_sorted['Longitude'].astype(str)+" "+arrests_sorted['Latitude'].astype(str)
arrests_sorted

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat,LONGLAT
5985472,9929805,2006-01-01,793.0,WEAPONS POSSESSION 3,118.0,DANGEROUS WEAPONS,PL 2650204,F,B,52,0.0,25-44,M,WHITE HISPANIC,1015192.0,257668.0,40.873868,-73.888119,POINT (-73.88811877499995 40.873867549000074),-73.88811877499995 40.873867549000074
5976830,9930311,2006-01-01,750.0,RESISTING ARREST,359.0,OFFENSES AGAINST PUBLIC ADMINISTRATION,PL 2053000,M,Q,111,0.0,45-64,M,ASIAN / PACIFIC ISLANDER,1046277.0,210432.0,40.744055,-73.776156,POINT (-73.77615584299997 40.74405453100008),-73.77615584299997 40.74405453100008
5980692,9929897,2006-01-01,779.0,"PUBLIC ADMINISTRATION,UNCLASSIFIED FELONY",126.0,MISCELLANEOUS PENAL LAW,PL 215510B,F,B,40,0.0,45-64,M,BLACK,1006737.0,233009.0,40.806211,-73.918774,POINT (-73.91877372999993 40.80621138200007),-73.91877372999993 40.80621138200007
5980694,9930087,2006-01-01,567.0,"MARIJUANA, POSSESSION 4 & 5",235.0,DANGEROUS DRUGS,PL 2211001,M,M,7,0.0,25-44,M,WHITE,987478.0,201620.0,40.720085,-73.988356,POINT (-73.98835630899998 40.72008467900002),-73.98835630899998 40.72008467900002
5983584,9930095,2006-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,19,0.0,18-24,M,WHITE,996157.0,222560.0,40.777552,-73.957009,POINT (-73.95700940399996 40.77755228400008),-73.95700940399996 40.77755228400008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256186,298672654,2024-12-31,793.0,WEAPONS POSSESSION 3,118.0,DANGEROUS WEAPONS,PL 2650201,F,K,75,2.0,45-64,M,BLACK,1019192.0,183434.0,40.670101,-73.874039,POINT (-73.874039 40.670101),-73.874039 40.670101
255113,298699290,2024-12-31,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,Q,102,0.0,45-64,M,WHITE,1031992.0,197141.0,40.707664,-73.827801,POINT (-73.827801 40.707664),-73.827801 40.707664
256145,298663611,2024-12-31,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL05110E2,F,B,40,0.0,25-44,M,BLACK,1003284.0,235725.0,40.813666,-73.931238,POINT (-73.93123754706842 40.81366588249614),-73.93123754706842 40.81366588249614
12651,298690452,2024-12-31,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,PL 1211200,F,B,40,0.0,25-44,M,BLACK,1009012.0,236134.0,40.814785,-73.910542,POINT (-73.910542 40.814785),-73.910542 40.814785
253806,298682165,2024-12-31,268.0,CRIMINAL MIS 2 & 3,121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1450502,F,Q,109,0.0,18-24,M,WHITE HISPANIC,1032084.0,216954.0,40.762045,-73.827329,POINT (-73.827329 40.762045),-73.827329 40.762045

In [12]:
arrests_sorted.columns = arrests_sorted.columns.to_series().replace({'ARREST_DATE':'DATE'})

complaints_subset.columns = complaints_subset.columns.to_series().replace({'CMPLNT_FR_DT':'DATE'})

In [13]:
complaints_subset

,CMPLNT_NUM,DATE,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,RPT_DT,KY_CD,OFNS_DESC,PD_CD,...,TRANSIT_DISTRICT,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX,LONGLAT
7308,45696867,2006-01-01,00:00:00,12/31/2006,23:59:00,40.0,04/14/2008,340,FRAUDS,718.0,...,NaN,40.811507,-73.922606,"(40.811507, -73.922606)",PATROL BORO BRONX,(null),25-44,BLACK,F,-73.922606 40.811507
83442,46101691,2006-01-01,00:00:00,03/01/2008,15:00:00,44.0,04/30/2008,112,THEFT-FRAUD,739.0,...,NaN,40.838528,-73.915334,"(40.838528, -73.915334)",PATROL BORO BRONX,(null),25-44,BLACK HISPANIC,F,-73.915334 40.838528
150747,52275241,2006-01-01,00:00:00,12/31/2007,00:00:00,49.0,10/16/2008,340,FRAUDS,718.0,...,NaN,40.855565,-73.865718,"(40.855565, -73.865718)",PATROL BORO BRONX,(null),25-44,UNKNOWN,M,-73.865718 40.855565
160989,38948518,2006-01-01,00:00:00,12/31/2006,00:00:00,49.0,02/05/2008,340,FRAUDS,718.0,...,NaN,40.861223,-73.860729,"(40.861223, -73.860729)",PATROL BORO BRONX,(null),25-44,WHITE HISPANIC,M,-73.860729 40.861223
169670,52517988,2006-01-01,00:00:00,12/31/2006,00:00:00,77.0,10/24/2008,116,SEX CRIMES,179.0,...,NaN,40.674496,-73.930571,"(40.6744956865259, -73.9305713255961)",PATROL BORO BKLYN NORTH,(null),<18,BLACK,F,-73.9305713255961 40.6744956865259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9375752,298704253,2024-12-31,23:25:00,12/31/2024,23:30:00,67.0,12/31/2024,118,DANGEROUS WEAPONS,792.0,...,NaN,40.657858,-73.916488,"(40.65785843797927, -73.91648767685969)",PATROL BORO BKLYN SOUTH,(null),UNKNOWN,UNKNOWN,E,-73.91648767685969 40.65785843797927
9126241,298692886,2024-12-31,23:30:00,NaN,(null),13.0,12/31/2024,107,BURGLARY,223.0,...,NaN,40.732922,-73.981277,"(40.732922, -73.981277)",PATROL BORO MAN SOUTH,(null),18-24,WHITE,F,-73.981277 40.732922
9181203,298703788,2024-12-31,23:30:00,12/31/2024,23:40:00,47.0,12/31/2024,578,HARRASSMENT 2,637.0,...,NaN,40.877125,-73.865602,"(40.877125, -73.865602)",PATROL BORO BRONX,(null),45-64,BLACK,F,-73.865602 40.877125
8996177,298704264,2024-12-31,23:37:00,12/31/2024,23:45:00,72.0,12/31/2024,106,FELONY ASSAULT,109.0,...,NaN,40.661646,-73.998435,"(40.661646, -73.998435)",PATROL BORO BKLYN SOUTH,(null),45-64,WHITE HISPANIC,F,-73.998435 40.661646
9146670,298712832,2024-12-31,23:45:00,12/31/2024,23:50:00,75.0,12/31/2024,125,OTHER STATE LAWS,847.0,...,NaN,40.656262,-73.891081,"(40.65626168022815, -73.8910808434055)",PATROL BORO BKLYN NORTH,(null),UNKNOWN,UNKNOWN,E,-73.8910808434055 40.65626168022815

# Complaints that result in arrests

Using date of the complaint / arrest and the longitude and latitude

In [14]:
print(arrests_sorted.columns)
print(complaints_subset.columns)

arrests_sorted.columns = arrests_sorted.columns.to_series().replace({'PERP_SEX':'SUSP_SEX','PERP_RACE':"SUSP_RACE","AGE_GROUP":"SUSP_AGE_GROUP"})

Index(['ARREST_KEY', 'DATE', 'PD_CD', 'PD_DESC', 'KY_CD', 'OFNS_DESC',
       'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT',
       'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'X_COORD_CD',
       'Y_COORD_CD', 'Latitude', 'Longitude', 'Lon_Lat', 'LONGLAT'],
      dtype='object')
Index(['CMPLNT_NUM', 'DATE', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT', 'CMPLNT_TO_TM',
       'ADDR_PCT_CD', 'RPT_DT', 'KY_CD', 'OFNS_DESC', 'PD_CD', 'PD_DESC',
       'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD', 'BORO_NM', 'LOC_OF_OCCUR_DESC',
       'PREM_TYP_DESC', 'JURIS_DESC', 'JURISDICTION_CODE', 'PARKS_NM',
       'HADEVELOPT', 'HOUSING_PSA', 'X_COORD_CD', 'Y_COORD_CD',
       'SUSP_AGE_GROUP', 'SUSP_RACE', 'SUSP_SEX', 'TRANSIT_DISTRICT',
       'Latitude', 'Longitude', 'Lat_Lon', 'PATROL_BORO', 'STATION_NAME',
       'VIC_AGE_GROUP', 'VIC_RACE', 'VIC_SEX', 'LONGLAT'],
      dtype='object')

In [15]:
print(arrests_sorted['SUSP_SEX'].unique())
print(arrests_sorted['SUSP_RACE'].unique())
print(arrests_sorted['SUSP_AGE_GROUP'].unique())

print(arrests_sorted['X_COORD_CD'])
print(arrests_sorted['OFNS_DESC'])
print(arrests_sorted['LAW_CAT_CD'].unique())

['M' 'F' 'U']
['WHITE HISPANIC' 'ASIAN / PACIFIC ISLANDER' 'BLACK' 'WHITE'
 'BLACK HISPANIC' 'UNKNOWN' 'OTHER' 'AMERICAN INDIAN/ALASKAN NATIVE']
['25-44' '45-64' '18-24' '<18' '65+' '314' '945' '932' '928' '895' '940'
 '896' '937' '936' '927' nan '921' '954' '931' '938' '952' '200' '338'
 '922' '740' '933' '894' '935' '925' '212' '918' '949' '237' '920' '924'
 '926' '951' '947' '912' 'UNKNOWN' '640' '939' '709' '316' '944' '816'
 '1922' '352' '1018' '942' '929' '708' '1024' '1948' '1048' '948' '194'
 '2007' '231' '1998' '956' '914' '946' '943' '1953' '909' '1942' '323'
 '1916' '339' '965' '1937' '1947' '1918' '1928' '1042' '2000' '934' '923'
 '812' '317' '808' '955' '320' '330' '446' '941' '910' '930' '959' '309'
 '723']
5985472    1015192.0
5976830    1046277.0
5980692    1006737.0
5980694     987478.0
5983584     996157.0
             ...
256186     1019192.0
255113     1031992.0
256145     1003284.0
12651      1009012.0
253806     1032084.0
Name: X_COORD_CD, Length: 5986025, dtype: float64
5985472                         DANGEROUS WEAPONS
5976830    OFFENSES AGAINST PUBLIC ADMINISTRATION
5980692                   MISCELLANEOUS PENAL LAW
5980694                           DANGEROUS DRUGS
5983584              ASSAULT 3 & RELATED OFFENSES
                            ...
256186                          DANGEROUS WEAPONS
255113                             FELONY ASSAULT
256145                   VEHICLE AND TRAFFIC LAWS
12651                              FELONY ASSAULT
253806             CRIMINAL MISCHIEF & RELATED OF
Name: OFNS_DESC, Length: 5986025, dtype: object
['F' 'M' nan 'I' 'V' '9' '(null)']

In [16]:
print(complaints_subset['SUSP_SEX'].unique())
print(complaints_subset['SUSP_RACE'].unique())
print(complaints_subset['SUSP_AGE_GROUP'].unique())
print(complaints_subset['X_COORD_CD'])
print(complaints_subset['OFNS_DESC'])
print(complaints_subset['LAW_CAT_CD'].unique())

['(null)' 'M' 'U' 'F']
['(null)' 'BLACK' 'UNKNOWN' 'WHITE HISPANIC' 'ASIAN / PACIFIC ISLANDER'
 'BLACK HISPANIC' 'WHITE' 'AMERICAN INDIAN/ALASKAN NATIVE' 'OTHER']
['(null)' '25-44' '45-64' '<18' 'UNKNOWN' '18-24' '65+' '231' '2014' '920'
 '245' '2015' '926' '2023' '296' '813' '2019' '623' '1024' '185' '940'
 '2530' '435' '2013' '175' '395' '1023' '455' '-5' '505' '-942' '275'
 '954' '1022' '1053' '1967' '2024' '375' '929' '935' '-969' '3030' '2021'
 '942' '-2' '-71' '938' '2017' '229' '1018' '538' '180' '934' '265' '639'
 '2016' '308' '-966' '925' '2018' '2010' '305' '2022' '2011' '2012' '958'
 '256' '1616' '-1' '2020' '529' '966' '-72' '941' '1017' '930' '225' '808'
 '535' '932' '2727' '928' '936' '980' '160' '955' '355' '-973' '1953'
 '965' '1019' '-947' '4646' '943' '165' '917' '2828' '2424' '-974' '1515'
 '292' '255' '952' '-5962' '931' '944' '-30' '1052' '1016' '933' '937'
 '-54' '-975' '939' '949' '947' '-979' '-941' '385' '485' '924' '1925'
 '-965' '1012' '327' '534' '1818' '-83' '-959' '921' '708' '416' '-63'
 '-961' '-80' '-951' '914' '4040' '945' '205' '953' '285' '454' '1976'
 '-978' '-67' '-972' '-939' '155' '912' '533' '32032' '900' '324' '532'
 '-924' '-10' '959' '923' '405' '-971' '-968' '528' '190' '927' '215'
 '951' '216' '3334' '-960' '922' '536' '495' '626' '582' '-64' '246' '445'
 '1007' '1933' '555' '635' '-47' '1014' '-946' '346' '-69' '235' '295'
 '518' '2009' '565' '525' '325' '3735' '-943' '546' '3434' '228' '5049'
 '1932' '545' '-3' '196' '1046' '948' '1056' '1956' '1011' '222' '-6'
 '-62' '3131' '625' '352' '1822' '2121' '2927' '540' '-66' '946' '-955'
 '-65' '956' '486' '3435' '-964' '537' '376' '522' '-976' '-956' '-12'
 '425' '902' '711' '1032' '164' '-42' '1020' '-49' '964' '354' '999' '530'
 '1975' '521' '972' '517' '1981' '3535' '915' '548' '967' '-953' '2223'
 '2525' '170' '1013' '810' '1919' '-962' '-952' '3636' '334' '456' '315'
 '-60' '335' '-55' '-33' '-981' '-977' '171' '1009' '4142' '1004' '-963'
 '-948' '-74' '655' '-928' '-76']
7308       1005674.0
83442      1007677.0
150747     1021396.0
160989     1022773.0
169670     1003509.0
             ...
9375752    1007421.0
9126241     989439.0
9181203    1021417.0
8996177     984684.0
9146670    1014471.0
Name: X_COORD_CD, Length: 9470313, dtype: float64
7308                  FRAUDS
83442            THEFT-FRAUD
150747                FRAUDS
160989                FRAUDS
169670            SEX CRIMES
                 ...
9375752    DANGEROUS WEAPONS
9126241             BURGLARY
9181203        HARRASSMENT 2
8996177       FELONY ASSAULT
9146670     OTHER STATE LAWS
Name: OFNS_DESC, Length: 9470313, dtype: object
['MISDEMEANOR' 'FELONY' 'VIOLATION']

In [17]:
complaints_subset['LAW_CAT_CD']=complaints_subset['LAW_CAT_CD'].str[0]

/var/folders/0d/v5wf93vd20j3t_d7spp38m5w0000gn/T/ipykernel_16995/2913081455.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  complaints_subset['LAW_CAT_CD']=complaints_subset['LAW_CAT_CD'].str[0]

In [18]:
arrest_complaints = pd.merge(arrests_sorted, complaints_subset, 
                             on=['DATE','LONGLAT','SUSP_SEX','SUSP_RACE','X_COORD_CD','Y_COORD_CD','JURISDICTION_CODE','LAW_CAT_CD'], how='inner')

In [19]:
arrest_complaints

,ARREST_KEY,DATE,PD_CD_x,PD_DESC_x,KY_CD_x,OFNS_DESC_x,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,...,SUSP_AGE_GROUP_y,TRANSIT_DISTRICT,Latitude_y,Longitude_y,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
0,238513925,2022-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,115,...,25-44,NaN,40.751091,-73.860642,"(40.751091, -73.860642)",PATROL BORO QUEENS NORTH,(null),25-44,WHITE HISPANIC,M
1,238513925,2022-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,115,...,25-44,NaN,40.751091,-73.860642,"(40.751091, -73.860642)",PATROL BORO QUEENS NORTH,(null),25-44,WHITE HISPANIC,M
2,238513921,2022-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,115,...,25-44,NaN,40.751091,-73.860642,"(40.751091, -73.860642)",PATROL BORO QUEENS NORTH,(null),25-44,WHITE HISPANIC,M
3,238513921,2022-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,115,...,25-44,NaN,40.751091,-73.860642,"(40.751091, -73.860642)",PATROL BORO QUEENS NORTH,(null),25-44,WHITE HISPANIC,M
4,238519081,2022-01-01,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,B,43,...,25-44,NaN,40.829142,-73.882666,"(40.829142, -73.882666)",PATROL BORO BRONX,(null),25-44,WHITE HISPANIC,F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351083,298706301,2024-12-31,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,M,14,...,25-44,NaN,40.753826,-73.980643,"(40.753826, -73.980643)",PATROL BORO MAN SOUTH,(null),25-44,BLACK HISPANIC,M
351084,298682157,2024-12-31,759.0,"PUBLIC ADMINISTATION,UNCLASS M",359.0,OFFENSES AGAINST PUBLIC ADMINI,PL 1950500,M,K,78,...,18-24,NaN,40.668146,-73.978894,"(40.668146, -73.978894)",PATROL BORO BKLYN SOUTH,(null),18-24,BLACK,M
351085,298672654,2024-12-31,793.0,WEAPONS POSSESSION 3,118.0,DANGEROUS WEAPONS,PL 2650201,F,K,75,...,45-64,NaN,40.670101,-73.874039,"(40.670101, -73.874039)",PATROL BORO BKLYN NORTH,(null),18-24,BLACK,F
351086,298699290,2024-12-31,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,Q,102,...,45-64,NaN,40.707664,-73.827801,"(40.707664, -73.827801)",PATROL BORO QUEENS SOUTH,(null),45-64,WHITE,M
351087,298663611,2024-12-31,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL05110E2,F,B,40,...,25-44,NaN,40.813666,-73.931238,"(40.81366588249614, -73.93123754706842)",PATROL BORO BRONX,(null),UNKNOWN,UNKNOWN,E

In [20]:
len(complaints)

9491946

In [21]:
len(arrest_complaints)

351088

In [22]:
arrest_complaints.columns

Index(['ARREST_KEY', 'DATE', 'PD_CD_x', 'PD_DESC_x', 'KY_CD_x', 'OFNS_DESC_x',
       'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT',
       'JURISDICTION_CODE', 'SUSP_AGE_GROUP_x', 'SUSP_SEX', 'SUSP_RACE',
       'X_COORD_CD', 'Y_COORD_CD', 'Latitude_x', 'Longitude_x', 'Lon_Lat',
       'LONGLAT', 'CMPLNT_NUM', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT', 'CMPLNT_TO_TM',
       'ADDR_PCT_CD', 'RPT_DT', 'KY_CD_y', 'OFNS_DESC_y', 'PD_CD_y',
       'PD_DESC_y', 'CRM_ATPT_CPTD_CD', 'BORO_NM', 'LOC_OF_OCCUR_DESC',
       'PREM_TYP_DESC', 'JURIS_DESC', 'PARKS_NM', 'HADEVELOPT', 'HOUSING_PSA',
       'SUSP_AGE_GROUP_y', 'TRANSIT_DISTRICT', 'Latitude_y', 'Longitude_y',
       'Lat_Lon', 'PATROL_BORO', 'STATION_NAME', 'VIC_AGE_GROUP', 'VIC_RACE',
       'VIC_SEX'],
      dtype='object')

In [23]:
arrest_complaints.groupby('BORO_NM').count()

,ARREST_KEY,DATE,PD_CD_x,PD_DESC_x,KY_CD_x,OFNS_DESC_x,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,...,SUSP_AGE_GROUP_y,TRANSIT_DISTRICT,Latitude_y,Longitude_y,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
BORO_NM,,,,,,,,,,,,,,,,,,,,,
(null),52,52,52,52,52,52,52,52,52,52,...,52,25,52,52,52,52,52,52,52,52
BRONX,82944,82944,82930,82944,82930,82944,82944,82944,82944,82944,...,82944,7506,82944,82944,82944,82944,82944,82944,82944,82944
BROOKLYN,92587,92587,92575,92587,92575,92587,92587,92587,92587,92587,...,92587,10902,92587,92587,92587,92587,92587,92587,92587,92587
MANHATTAN,87527,87527,87517,87527,87516,87527,87527,87527,87527,87527,...,87527,9075,87527,87527,87527,87527,87527,87527,87527,87527
QUEENS,74506,74506,74495,74506,74492,74506,74506,74506,74506,74506,...,74506,2872,74504,74504,74504,74506,74506,74506,74506,74506
STATEN ISLAND,13472,13472,13468,13472,13468,13472,13472,13472,13472,13472,...,13472,0,13472,13472,13472,13472,13472,13472,13472,13472

In [24]:
arrest_complaints.groupby('ARREST_BORO').count()

,ARREST_KEY,DATE,PD_CD_x,PD_DESC_x,KY_CD_x,OFNS_DESC_x,LAW_CODE,LAW_CAT_CD,ARREST_PRECINCT,JURISDICTION_CODE,...,SUSP_AGE_GROUP_y,TRANSIT_DISTRICT,Latitude_y,Longitude_y,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
ARREST_BORO,,,,,,,,,,,,,,,,,,,,,
B,82948,82948,82934,82948,82934,82948,82948,82948,82948,82948,...,82948,7512,82948,82948,82948,82948,82948,82948,82948,82948
K,92609,92609,92597,92609,92597,92609,92609,92609,92609,92609,...,92609,10921,92609,92609,92609,92609,92609,92609,92609,92609
M,87547,87547,87537,87547,87536,87547,87547,87547,87547,87547,...,87547,9081,87547,87547,87547,87547,87547,87547,87547,87547
Q,74515,74515,74504,74515,74501,74515,74515,74515,74515,74515,...,74515,2866,74513,74513,74513,74515,74515,74515,74515,74515
S,13469,13469,13465,13469,13465,13469,13469,13469,13469,13469,...,13469,0,13469,13469,13469,13469,13469,13469,13469,13469

In [25]:
arrest_complaints=arrest_complaints.drop(columns=['BORO_NM'])

In [26]:
arrest_complaints.columns

Index(['ARREST_KEY', 'DATE', 'PD_CD_x', 'PD_DESC_x', 'KY_CD_x', 'OFNS_DESC_x',
       'LAW_CODE', 'LAW_CAT_CD', 'ARREST_BORO', 'ARREST_PRECINCT',
       'JURISDICTION_CODE', 'SUSP_AGE_GROUP_x', 'SUSP_SEX', 'SUSP_RACE',
       'X_COORD_CD', 'Y_COORD_CD', 'Latitude_x', 'Longitude_x', 'Lon_Lat',
       'LONGLAT', 'CMPLNT_NUM', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT', 'CMPLNT_TO_TM',
       'ADDR_PCT_CD', 'RPT_DT', 'KY_CD_y', 'OFNS_DESC_y', 'PD_CD_y',
       'PD_DESC_y', 'CRM_ATPT_CPTD_CD', 'LOC_OF_OCCUR_DESC', 'PREM_TYP_DESC',
       'JURIS_DESC', 'PARKS_NM', 'HADEVELOPT', 'HOUSING_PSA',
       'SUSP_AGE_GROUP_y', 'TRANSIT_DISTRICT', 'Latitude_y', 'Longitude_y',
       'Lat_Lon', 'PATROL_BORO', 'STATION_NAME', 'VIC_AGE_GROUP', 'VIC_RACE',
       'VIC_SEX'],
      dtype='object')

In [27]:
arrest_complaints.groupby('SUSP_SEX').count()

,ARREST_KEY,DATE,PD_CD_x,PD_DESC_x,KY_CD_x,OFNS_DESC_x,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,...,SUSP_AGE_GROUP_y,TRANSIT_DISTRICT,Latitude_y,Longitude_y,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
SUSP_SEX,,,,,,,,,,,,,,,,,,,,,
F,69635,69635,69623,69635,69623,69635,69635,69635,69635,69635,...,69635,1426,69634,69634,69634,69635,69635,69635,69635,69635
M,280142,280142,280103,280142,280099,280142,280142,280142,280142,280142,...,280142,28920,280141,280141,280141,280142,280142,280142,280142,280142
U,1311,1311,1311,1311,1311,1311,1311,1311,1311,1311,...,1311,34,1311,1311,1311,1311,1311,1311,1311,1311